name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./input
    
    steps:
      - name: Replace json
        run: echo ${{ toJson(github.event.client_payload.tokens) }} > od.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
  
