name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Go to input directory
        run: |
             mkdir input
             cd input
             
      - name: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "od.json"
          json: toJson(github.event.client_payload.tokens)
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
  
