name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkOut
        uses: actions/checkout@main
      - name: Go to input folder
        run: cd input
      - name: Replace json
        run: echo ${{ toJson(github.event.client_payload.tokens) }} od.json

      - name: Commit gile
        run : git config --global user.email "girish.h@ymedialabs.com"
              git config --global user.name "Girish" |
              git commit -m "Updated tokens" | git push
  
