name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkOut
        uses: actions/checkout@main
      - name : Create folder
        run : mkdir input
      - name: Replace json
        run: cd input | echo ${{ toJson(github.event.client_payload.tokens) }} > od.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
  
