name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkOut
        uses: actions/checkout@main
      - name: Go to input folder
        run: cd input
      - name: Replace json
        run: echo ${{ toJson(github.event.client_payload.tokens) }} od.json
      - name: Come out of input folder
        run: cd ..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create token
