name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-tokens]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create token file using data from Figma
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.tokens) }}
        run: echo "$PAYLOAD_CONTEXT"

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "input/od.json"
          json: ${{ toJson(github.event.client_payload.tokens) }}
        
      - uses: actions/checkout@v2
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}
